/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.forum.features;

import com.forum.database.BaiDangForumDAO;

/**
 *
 * @author 21H1 HNQA
 */
public class PostingFeaturePanel extends javax.swing.JPanel {

    /**
     * Creates new form PostingFeaturePanel
     */
    public PostingFeaturePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleInCentralLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        contentLabel = new javax.swing.JLabel();
        jScrollPaneOfContent = new javax.swing.JScrollPane();
        jTextAreaOfContent = new javax.swing.JTextArea();
        postButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPaneOfTitle = new javax.swing.JScrollPane();
        jTextAreaOfTitle = new javax.swing.JTextArea();
        uitlogoLabel = new javax.swing.JLabel();
        ecoForumLabel = new javax.swing.JLabel();
        forumIconLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 245, 231));

        titleInCentralLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        titleInCentralLabel.setForeground(new java.awt.Color(30, 30, 14));
        titleInCentralLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleInCentralLabel.setText("ĐĂNG BÀI");

        titleLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("Title");

        contentLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        contentLabel.setForeground(new java.awt.Color(5, 13, 13));
        contentLabel.setText("Content");

        jScrollPaneOfContent.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaOfContent.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaOfContent.setColumns(20);
        jTextAreaOfContent.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaOfContent.setLineWrap(true);
        jTextAreaOfContent.setRows(5);
        jTextAreaOfContent.setText("Nhập nội dung của bài đăng tại đây");
        jTextAreaOfContent.setToolTipText("Nhập nội dung bài đăng");
        jTextAreaOfContent.setWrapStyleWord(true);
        jTextAreaOfContent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextAreaOfContentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAreaOfContentFocusLost(evt);
            }
        });
        jTextAreaOfContent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAreaOfContentMouseClicked(evt);
            }
        });
        jScrollPaneOfContent.setViewportView(jTextAreaOfContent);

        postButton.setBackground(new java.awt.Color(204, 204, 204));
        postButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        postButton.setForeground(new java.awt.Color(0, 0, 0));
        postButton.setText("Post");
        postButton.setFocusable(false);
        postButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postButtonMouseClicked(evt);
            }
        });
        postButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(204, 204, 204));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(0, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.setFocusable(false);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jScrollPaneOfTitle.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneOfTitle.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPaneOfTitle.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaOfTitle.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaOfTitle.setColumns(20);
        jTextAreaOfTitle.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaOfTitle.setLineWrap(true);
        jTextAreaOfTitle.setRows(5);
        jTextAreaOfTitle.setText("Nhập tiêu đề của bài đăng tại đây");
        jTextAreaOfTitle.setToolTipText("Nhập tiêu đề bài đăng");
        jTextAreaOfTitle.setWrapStyleWord(true);
        jTextAreaOfTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextAreaOfTitleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAreaOfTitleFocusLost(evt);
            }
        });
        jTextAreaOfTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAreaOfTitleMouseClicked(evt);
            }
        });
        jScrollPaneOfTitle.setViewportView(jTextAreaOfTitle);

        uitlogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uitlogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uit(3).png"))); // NOI18N

        ecoForumLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ecoForumLabel.setForeground(new java.awt.Color(80, 80, 181));
        ecoForumLabel.setText("ECO-FORUM");

        forumIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forumIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postingforum (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneOfTitle)
                            .addComponent(jScrollPaneOfContent))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(postButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(uitlogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)
                        .addComponent(titleInCentralLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ecoForumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(forumIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(contentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ecoForumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forumIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(uitlogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(titleInCentralLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32)))
                .addGap(18, 18, 18)
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneOfTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(contentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneOfContent, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton)
                    .addComponent(postButton))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void postButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jTextAreaOfTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaOfTitleMouseClicked
        if(jTextAreaOfTitle.getText().equals("Nhập tiêu đề của bài đăng tại đây")){
            jTextAreaOfTitle.setText("");
        }
    }//GEN-LAST:event_jTextAreaOfTitleMouseClicked

    private void jTextAreaOfTitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaOfTitleFocusLost
        if(jTextAreaOfTitle.getText().isEmpty()){
            jTextAreaOfTitle.setText("Nhập tiêu đề của bài đăng tại đây");
        }
    }//GEN-LAST:event_jTextAreaOfTitleFocusLost

    private void jTextAreaOfTitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaOfTitleFocusGained
        jTextAreaOfTitle.getCaret().setVisible(true);
    }//GEN-LAST:event_jTextAreaOfTitleFocusGained

    private void jTextAreaOfContentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaOfContentMouseClicked
        if(jTextAreaOfContent.getText().equals("Nhập nội dung của bài đăng tại đây")){
            jTextAreaOfContent.setText("");
        }
    }//GEN-LAST:event_jTextAreaOfContentMouseClicked

    private void jTextAreaOfContentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaOfContentFocusGained
        jTextAreaOfContent.getCaret().setVisible(true);
    }//GEN-LAST:event_jTextAreaOfContentFocusGained

    private void jTextAreaOfContentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaOfContentFocusLost
        if(jTextAreaOfContent.getText().isEmpty()){
            jTextAreaOfContent.setText("Nhập nội dung của bài đăng tại đây");
        }
    }//GEN-LAST:event_jTextAreaOfContentFocusLost

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        com.uiteco.contentPanels.ForumPanel panel1 = (com.uiteco.contentPanels.ForumPanel)getParent(); 
        panel1.removeAll();
        panel1._initComponents();
//        this.revalidate();
//        this.repaint();
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void postButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postButtonMouseClicked
        /*lưu thông tin vào csdl*/
        String content = jTextAreaOfContent.getText();
        String title = jTextAreaOfTitle.getText();
        int viewNumber = 0;
        int replyNumber = 0;
        String username = com.uiteco.main.App.getSession().getUsername();
        System.out.println("User is logging: " + username);
        BaiDangForumDAO.insertIntoDatabaseWhenClickPosting(username, content, title, viewNumber, replyNumber);
        /*load dữ liệu từ csdl để hiển thị lại giao diện chính của forum*/
        com.uiteco.contentPanels.ForumPanel panel1 = (com.uiteco.contentPanels.ForumPanel)getParent(); 
        panel1.removeAll();
        panel1._initComponents();
        panel1.getPostListPanel2().loadPostForumFromDatabaseIntoListPost();
//        this.revalidate();
//        this.repaint();
    }//GEN-LAST:event_postButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel contentLabel;
    private javax.swing.JLabel ecoForumLabel;
    private javax.swing.JLabel forumIconLabel;
    private javax.swing.JScrollPane jScrollPaneOfContent;
    private javax.swing.JScrollPane jScrollPaneOfTitle;
    private javax.swing.JTextArea jTextAreaOfContent;
    private javax.swing.JTextArea jTextAreaOfTitle;
    private javax.swing.JButton postButton;
    private javax.swing.JLabel titleInCentralLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel uitlogoLabel;
    // End of variables declaration//GEN-END:variables
}
