/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.contentPanels;

/**
 *
 * @author nddmi
 */
public class TaiKhoanPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaiKhoanPanel
     */
    public TaiKhoanPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new com.raven.scroll.ScrollPaneWin11();
        containerPanel = new com.uiteco.components.RoundedGradientPanel();
        personalInformation1 = new com.uiteco.ofTaiKhoanPanel.PersonalInformation();
        adminSection1 = new com.uiteco.ofTaiKhoanPanel.AdminSection();

        setLayout(new java.awt.GridLayout());

        scrollPane.setBorder(null);

        containerPanel.setColor1(new java.awt.Color(255, 255, 255));
        containerPanel.setColor2(new java.awt.Color(255, 255, 255));
        containerPanel.setLayout(new javax.swing.BoxLayout(containerPanel, javax.swing.BoxLayout.Y_AXIS));
        containerPanel.add(personalInformation1);
        containerPanel.add(adminSection1);

        scrollPane.setViewportView(containerPanel);

        add(scrollPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.uiteco.ofTaiKhoanPanel.AdminSection adminSection1;
    private com.uiteco.components.RoundedGradientPanel containerPanel;
    private com.uiteco.ofTaiKhoanPanel.PersonalInformation personalInformation1;
    private com.raven.scroll.ScrollPaneWin11 scrollPane;
    // End of variables declaration//GEN-END:variables
}
