/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.ofTaiKhoanPanel.createPost;

/**
 *
 * @author nddmi
 */
public class CreatePostUI extends javax.swing.JPanel {

    public static final String INSTANCE_NAME = "createPostUI";
    
    /**
     * Creates new form CreatePost
     */
    public CreatePostUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scrollPaneWin111 = new com.raven.scroll.ScrollPaneWin11();
        containerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        roundedPanel1 = new com.uiteco.components.RoundedPanel();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        roundedPanel2 = new com.uiteco.components.RoundedPanel();
        jTextPane2 = new javax.swing.JTextPane();
        utilPanel = new com.uiteco.components.RoundedGradientPanel();
        imgBtn = new com.uiteco.components.RoundedPanel();
        tagBtn = new com.uiteco.components.RoundedPanel();
        submitBtn = new com.uiteco.components.RoundedPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(1, 0));

        scrollPaneWin111.setBorder(null);

        containerPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel1.setText("Tiêu đề");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 10, 0);
        containerPanel.add(jLabel1, gridBagConstraints);

        roundedPanel1.setPreferredSize(new java.awt.Dimension(810, 100));
        roundedPanel1.setRoundBottomLeft(12);
        roundedPanel1.setRoundBottomRight(12);
        roundedPanel1.setRoundTopLeft(12);
        roundedPanel1.setRoundTopRight(12);

        jTextPane1.setOpaque(false);

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        containerPanel.add(roundedPanel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel2.setText("Nội dung");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 10, 0);
        containerPanel.add(jLabel2, gridBagConstraints);

        roundedPanel2.setRoundBottomLeft(12);
        roundedPanel2.setRoundBottomRight(12);
        roundedPanel2.setRoundTopLeft(12);
        roundedPanel2.setRoundTopRight(12);

        jTextPane2.setOpaque(false);

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel2Layout.createSequentialGroup()
                .addComponent(jTextPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        containerPanel.add(roundedPanel2, gridBagConstraints);

        utilPanel.setColor1(new java.awt.Color(255, 255, 255));
        utilPanel.setColor2(new java.awt.Color(153, 153, 153));
        utilPanel.setDirection(com.uiteco.components.RoundedGradientPanel.Direction.HORIZONTAL);
        utilPanel.setPreferredSize(new java.awt.Dimension(750, 75));
        utilPanel.setRoundBottomLeft(15);
        utilPanel.setRoundBottomRight(15);
        utilPanel.setRoundTopLeft(15);
        utilPanel.setRoundTopRight(15);
        utilPanel.setLayout(new java.awt.GridBagLayout());

        imgBtn.setBackground(new java.awt.Color(255, 255, 255));
        imgBtn.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout imgBtnLayout = new javax.swing.GroupLayout(imgBtn);
        imgBtn.setLayout(imgBtnLayout);
        imgBtnLayout.setHorizontalGroup(
            imgBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imgBtnLayout.setVerticalGroup(
            imgBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        utilPanel.add(imgBtn, gridBagConstraints);

        tagBtn.setBackground(new java.awt.Color(255, 102, 102));
        tagBtn.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout tagBtnLayout = new javax.swing.GroupLayout(tagBtn);
        tagBtn.setLayout(tagBtnLayout);
        tagBtnLayout.setHorizontalGroup(
            tagBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tagBtnLayout.setVerticalGroup(
            tagBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        utilPanel.add(tagBtn, gridBagConstraints);

        submitBtn.setBackground(new java.awt.Color(255, 51, 51));
        submitBtn.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout submitBtnLayout = new javax.swing.GroupLayout(submitBtn);
        submitBtn.setLayout(submitBtnLayout);
        submitBtnLayout.setHorizontalGroup(
            submitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        submitBtnLayout.setVerticalGroup(
            submitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 15);
        utilPanel.add(submitBtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(30, 20, 15, 20);
        containerPanel.add(utilPanel, gridBagConstraints);

        scrollPaneWin111.setViewportView(containerPanel);

        add(scrollPaneWin111);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerPanel;
    private com.uiteco.components.RoundedPanel imgBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private com.uiteco.components.RoundedPanel roundedPanel1;
    private com.uiteco.components.RoundedPanel roundedPanel2;
    private com.raven.scroll.ScrollPaneWin11 scrollPaneWin111;
    private com.uiteco.components.RoundedPanel submitBtn;
    private com.uiteco.components.RoundedPanel tagBtn;
    private com.uiteco.components.RoundedGradientPanel utilPanel;
    // End of variables declaration//GEN-END:variables
}
