/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.ofTaiKhoanPanel.createPost;

import static com.uiteco.ofSuKienPanel.SuKienDAO.createSuKien;
import java.sql.SQLException;
import com.uiteco.main.App;
import com.uiteco.ofSuKienPanel.SuKienModel;
import com.uiteco.ofSuKienPanel.detailed.NullSuKienModelException;
import com.uiteco.ofSuKienPanel.detailed.SuKienDetailScrollPane;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.Set;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Popup;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.border.LineBorder;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import javax.swing.text.BadLocationException;

/**
 *
 * @author nddmi
 */
public class CreatePostUI extends javax.swing.JPanel {

    /**
     *
     */
    private class TitleDocListener implements DocumentListener {

        public static int charCountLimit = 250;

        @Override
        public void insertUpdate(DocumentEvent e) {
            limitCharacters();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            updateCharacterCount(false);
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            // Not needed for character count, can be left empty
        }

        private void updateCharacterCount(boolean isInsert) {
            int charCount = title.getDocument().getLength();
            titleCharCountLabel.setText(String.valueOf(charCount));
        }

        private void limitCharacters() {
            int currentLength = title.getDocument().getLength();
            if (currentLength > charCountLimit) {
                SwingUtilities.invokeLater(() -> {
                    try {
                        title.getDocument().remove(charCountLimit, currentLength - charCountLimit);
                    } catch (BadLocationException e) {
                        e.printStackTrace();
                    }
                });
            } else {
                updateCharacterCount(true);
            }
        }
    }

    /**
     * Variables of CreatePostUI
     */
    public static final String INSTANCE_NAME = "createPostUI";

    private Popup pup;
    private TagSelector tagSelector;
    private ImageSelector imageSelector;

    /**
     * Creates new form CreatePost
     */
    public CreatePostUI() {
        initComponents();

        try {
            tagSelector = new TagSelector();
            imageSelector = new ImageSelector();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đã có lỗi xảy ra khi hiển thị tag", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

        Timer timer = new Timer(1000, e -> {
            String currentTime = new SimpleDateFormat("HH:mm").format(new Date());
            jLabel8.setText(currentTime);
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        masterScrollPane = new com.raven.scroll.ScrollPaneWin11();
        containerPanel = new javax.swing.JPanel();
        masterTextPanel = new com.uiteco.components.RoundedPanel();
        roundedPanel1 = new com.uiteco.components.RoundedPanel();
        roundedPanel4 = new com.uiteco.components.RoundedPanel();
        title = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        titleCharCountLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        roundedPanel5 = new com.uiteco.components.RoundedPanel();
        contentScrollPane = new com.raven.scroll.ScrollPaneWin11();
        content = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        roundedImagePanel3 = new com.uiteco.components.RoundedImagePanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        posterInfo = new com.uiteco.components.RoundedPanel();
        utilPanel = new com.uiteco.components.RoundedGradientPanel();
        imgBtn = new com.uiteco.components.RoundedImagePanel();
        tagBtn = new com.uiteco.components.RoundedImagePanel();
        previewBtn = new com.uiteco.components.RoundedImagePanel();
        submitBtn = new com.uiteco.components.RoundedImagePanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        masterScrollPane.setBorder(null);

        containerPanel.setBackground(new java.awt.Color(255, 255, 255));
        containerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 0, 5));
        containerPanel.setPreferredSize(new java.awt.Dimension(810, 1188));
        containerPanel.setLayout(new java.awt.GridBagLayout());

        masterTextPanel.setBackground(new java.awt.Color(242, 243, 244));
        //roundedPanel2.setPreferredSize(new java.awt.Dimension(810, 767));
        masterTextPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        masterTextPanel.setPreferredSize(null);
        masterTextPanel.setRoundBottomLeft(12);
        masterTextPanel.setRoundBottomRight(12);
        masterTextPanel.setRoundTopLeft(12);
        masterTextPanel.setRoundTopRight(12);

        roundedPanel1.setBackground(new java.awt.Color(240, 242, 245));
        roundedPanel1.setRoundBottomLeft(20);
        roundedPanel1.setRoundBottomRight(20);
        roundedPanel1.setRoundTopLeft(20);
        roundedPanel1.setRoundTopRight(20);

        roundedPanel4.setBackground(new java.awt.Color(204, 204, 204));
        roundedPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        roundedPanel4.setPreferredSize(new java.awt.Dimension(703, 150));
        roundedPanel4.setRoundBottomLeft(30);
        roundedPanel4.setRoundBottomRight(30);
        roundedPanel4.setRoundTopLeft(30);
        roundedPanel4.setRoundTopRight(30);

        title.setColumns(20);
        title.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        title.setLineWrap(true);
        title.setRows(5);
        title.setWrapStyleWord(true);
        title.setBorder(null);
        title.setOpaque(false);
        title.getDocument().addDocumentListener(new TitleDocListener());

        javax.swing.GroupLayout roundedPanel4Layout = new javax.swing.GroupLayout(roundedPanel4);
        roundedPanel4.setLayout(roundedPanel4Layout);
        roundedPanel4Layout.setHorizontalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title)
        );
        roundedPanel4Layout.setVerticalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(5, 5, 5));
        jLabel4.setText("Tiêu đề bài viết:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.textInactiveText);
        jLabel7.setText("Số ký tự: ");

        titleCharCountLabel.setFont(new java.awt.Font("Segoe UI Variable", 0, 13)); // NOI18N
        titleCharCountLabel.setForeground(java.awt.SystemColor.textInactiveText);
        titleCharCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleCharCountLabel.setText("0");

        jLabel9.setFont(new java.awt.Font("Segoe UI Variable", 0, 13)); // NOI18N
        jLabel9.setForeground(java.awt.SystemColor.textInactiveText);
        jLabel9.setText(String.valueOf("/ " + TitleDocListener.charCountLimit));

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(roundedPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleCharCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)))
                .addGap(11, 11, 11))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(titleCharCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 5, 5));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-edit-24.png"))); // NOI18N
        jLabel2.setText("Nhập Nội dung:");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        roundedPanel5.setBackground(new java.awt.Color(51, 51, 51));
        roundedPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 20, 20));
        roundedPanel5.setRoundBottomLeft(70);
        roundedPanel5.setRoundBottomRight(70);
        roundedPanel5.setRoundTopLeft(70);
        roundedPanel5.setRoundTopRight(70);

        content.setColumns(20);
        content.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        content.setLineWrap(true);
        content.setRows(5);
        content.setWrapStyleWord(true);
        contentScrollPane.setViewportView(content);

        javax.swing.GroupLayout roundedPanel5Layout = new javax.swing.GroupLayout(roundedPanel5);
        roundedPanel5.setLayout(roundedPanel5Layout);
        roundedPanel5Layout.setHorizontalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roundedPanel5Layout.setVerticalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(5, 5, 5));
        jLabel3.setText("Người đăng: ");

        roundedImagePanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        roundedImagePanel3.setToolTipText("Quyền kiểm soát bài viết thuộc về Trường Đại học Công nghệ Thông tin");
        roundedImagePanel3.setImage(new javax.swing.ImageIcon(getClass().getResource("/uit-cropped.jpg"))); // NOI18N
        roundedImagePanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        roundedImagePanel3.setPreferredSize(new java.awt.Dimension(100, 100));
        roundedImagePanel3.setRoundBottomLeft(10);
        roundedImagePanel3.setRoundBottomRight(10);
        roundedImagePanel3.setRoundTopLeft(10);
        roundedImagePanel3.setRoundTopRight(10);

        javax.swing.GroupLayout roundedImagePanel3Layout = new javax.swing.GroupLayout(roundedImagePanel3);
        roundedImagePanel3.setLayout(roundedImagePanel3Layout);
        roundedImagePanel3Layout.setHorizontalGroup(
            roundedImagePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        roundedImagePanel3Layout.setVerticalGroup(
            roundedImagePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("- Admin -");

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-email-24.png"))); // NOI18N
        jLabel1.setText(App.getSession().getEmail());

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-username-24.png"))); // NOI18N
        jLabel6.setText(App.getSession().getUsername());

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout masterTextPanelLayout = new javax.swing.GroupLayout(masterTextPanel);
        masterTextPanel.setLayout(masterTextPanelLayout);
        masterTextPanelLayout.setHorizontalGroup(
            masterTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterTextPanelLayout.createSequentialGroup()
                .addGroup(masterTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(masterTextPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(masterTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(masterTextPanelLayout.createSequentialGroup()
                                .addGroup(masterTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(masterTextPanelLayout.createSequentialGroup()
                                        .addComponent(roundedImagePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(masterTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addGroup(masterTextPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(roundedPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        masterTextPanelLayout.setVerticalGroup(
            masterTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masterTextPanelLayout.createSequentialGroup()
                .addGroup(masterTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(masterTextPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedImagePanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        containerPanel.add(masterTextPanel, gridBagConstraints);

        posterInfo.setBackground(new java.awt.Color(255, 255, 255));
        posterInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        posterInfo.setLayout(new java.awt.GridLayout(4, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        containerPanel.add(posterInfo, gridBagConstraints);

        masterScrollPane.setViewportView(containerPanel);
        containerPanel.setPreferredSize(null);

        add(masterScrollPane);

        utilPanel.setBackground(new java.awt.Color(255, 255, 204));
        utilPanel.setBorder(null);
        utilPanel.setColor1(new java.awt.Color(33, 33, 33));
        utilPanel.setColor2(new java.awt.Color(33, 33, 33));
        utilPanel.setDirection(com.uiteco.components.RoundedGradientPanel.Direction.HORIZONTAL);
        utilPanel.setPreferredSize(new java.awt.Dimension(750, 50));
        utilPanel.setLayout(new java.awt.GridBagLayout());
        //utilPanel.setVisible(false);

        imgBtn.setToolTipText("Đính kèm ảnh");
        imgBtn.setImage(new javax.swing.ImageIcon(getClass().getResource("/icons8-image-48.png"))); // NOI18N
        imgBtn.setMinimumSize(new java.awt.Dimension(40, 40));
        imgBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        imgBtn.setRoundBottomLeft(5);
        imgBtn.setRoundBottomRight(5);
        imgBtn.setRoundTopLeft(5);
        imgBtn.setRoundTopRight(5);
        imgBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout imgBtnLayout = new javax.swing.GroupLayout(imgBtn);
        imgBtn.setLayout(imgBtnLayout);
        imgBtnLayout.setHorizontalGroup(
            imgBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        imgBtnLayout.setVerticalGroup(
            imgBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        utilPanel.add(imgBtn, gridBagConstraints);

        tagBtn.setToolTipText("Gắn thẻ sự kiện");
        tagBtn.setImage(new javax.swing.ImageIcon(getClass().getResource("/icons8-tags-48.png"))); // NOI18N
        tagBtn.setMinimumSize(new java.awt.Dimension(40, 40));
        tagBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        tagBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tagBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tagBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tagBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout tagBtnLayout = new javax.swing.GroupLayout(tagBtn);
        tagBtn.setLayout(tagBtnLayout);
        tagBtnLayout.setHorizontalGroup(
            tagBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        tagBtnLayout.setVerticalGroup(
            tagBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        utilPanel.add(tagBtn, gridBagConstraints);

        previewBtn.setToolTipText("Xem trước bài viết");
        previewBtn.setImage(new javax.swing.ImageIcon(getClass().getResource("/icons8-file-preview-48.png"))); // NOI18N
        previewBtn.setMinimumSize(new java.awt.Dimension(40, 40));
        previewBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        previewBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                previewBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                previewBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout previewBtnLayout = new javax.swing.GroupLayout(previewBtn);
        previewBtn.setLayout(previewBtnLayout);
        previewBtnLayout.setHorizontalGroup(
            previewBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        previewBtnLayout.setVerticalGroup(
            previewBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        utilPanel.add(previewBtn, new java.awt.GridBagConstraints());

        submitBtn.setToolTipText("Đăng tải bài viết");
        submitBtn.setImage(new javax.swing.ImageIcon(getClass().getResource("/icons8-paper-plane-48.png"))); // NOI18N
        submitBtn.setMinimumSize(new java.awt.Dimension(40, 40));
        submitBtn.setPreferredSize(new java.awt.Dimension(35, 35));
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout submitBtnLayout = new javax.swing.GroupLayout(submitBtn);
        submitBtn.setLayout(submitBtnLayout);
        submitBtnLayout.setHorizontalGroup(
            submitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        submitBtnLayout.setVerticalGroup(
            submitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 720, 0, 0);
        utilPanel.add(submitBtn, gridBagConstraints);

        add(utilPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked
        // TODO add your handling code here:
        _createPost();
    }//GEN-LAST:event_submitBtnMouseClicked

    private void imgBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBtnMouseEntered
        // TODO add your handling code here:
        imgBtn.setBorder(new LineBorder(Color.WHITE, 2, true));
    }//GEN-LAST:event_imgBtnMouseEntered

    private void imgBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBtnMouseExited
        // TODO add your handling code here:
        imgBtn.setBorder(null);
    }//GEN-LAST:event_imgBtnMouseExited

    private void tagBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tagBtnMouseEntered
        // TODO add your handling code here:
        tagBtn.setBorder(new LineBorder(Color.WHITE, 2, true));
    }//GEN-LAST:event_tagBtnMouseEntered

    private void tagBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tagBtnMouseExited
        // TODO add your handling code here:
        tagBtn.setBorder(null);
    }//GEN-LAST:event_tagBtnMouseExited

    private void submitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseEntered
        // TODO add your handling code here:
        submitBtn.setBorder(new LineBorder(Color.WHITE, 2, true));
    }//GEN-LAST:event_submitBtnMouseEntered

    private void submitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseExited
        // TODO add your handling code here:
        submitBtn.setBorder(null);
    }//GEN-LAST:event_submitBtnMouseExited

    private void previewBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewBtnMouseEntered
        // TODO add your handling code here:
        previewBtn.setBorder(new LineBorder(Color.WHITE, 2, true));
    }//GEN-LAST:event_previewBtnMouseEntered

    private void previewBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewBtnMouseExited
        // TODO add your handling code here:
        previewBtn.setBorder(null);
    }//GEN-LAST:event_previewBtnMouseExited

    private void tagBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tagBtnMouseClicked
        // TODO add your handling code here:
        _showTagSelector();
    }//GEN-LAST:event_tagBtnMouseClicked

    private void imgBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBtnMouseClicked
        // TODO add your handling code here:
        _showImageSelector();
    }//GEN-LAST:event_imgBtnMouseClicked

    private void previewBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewBtnMouseClicked
        // TODO add your handling code here:
        _showPreview();
    }//GEN-LAST:event_previewBtnMouseClicked

    private void _clear() {
        title.setText("");
        content.setText("");
        masterScrollPane.getViewport().revalidate();
        masterScrollPane.getViewport().repaint();
        masterScrollPane.revalidate();
        masterScrollPane.repaint();
    }

    private void _exit() {
        App.getMainFrame().getContentPanel().showComponentAndTrimHistory("taiKhoanPanel");
        App.getMainFrame().getRightPanel().showComponentAndTrimHistory("taiKhoanRightPanel");
        masterScrollPane.scrollToTop();
        contentScrollPane.scrollToTop();
    }

    private void _createPost() {
        try {
            String title = this.title.getText();
            String content = this.content.getText();
            if (title.length() == 0) {
                JOptionPane.showMessageDialog(this, "Nhập tiêu đề", "Vui lòng điền đầy đủ thông tin", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (content.length() == 0) {
                JOptionPane.showMessageDialog(this, "Nhập nội dung", "Vui lòng điền đầy đủ thông tin", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int accountID = App.getSession().getAccountID();
            Set<String> tags = tagSelector.getSelectedTags();
            ImageIcon thumbnail = imageSelector.getThumbnail();

            if (thumbnail == null) {
                if (JOptionPane.showConfirmDialog(
                        App.getMainFrame(),
                        "Bạn có muốn tiếp tục đăng bài?",
                        "Bài đăng chưa có thumbnail",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                ) == JOptionPane.NO_OPTION) {
                    return;
                }
            }

            List<ImageIcon> images = imageSelector.getSelectedImages();

            createSuKien(title, content, accountID, tags, images, thumbnail, null);

            if (!(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đăng tải bài viết", "Xác nhận", JOptionPane.OK_CANCEL_OPTION)
                    == JOptionPane.OK_OPTION)) {
                return;
            }

            JOptionPane.showMessageDialog(this, "Đăng bài viết thành công", "Thành công", JOptionPane.PLAIN_MESSAGE);
            _clear();
            _exit();
        } catch (SQLException | IOException e) {
            e.printStackTrace();
            String errMsg = e.getMessage();
            JOptionPane.showMessageDialog(this, errMsg, "Đã có lỗi xảy ra khi đăng bài", JOptionPane.ERROR_MESSAGE);
            _exit();
        }
    }

    private void _showTagSelector() {
        _createDialog("Tag", tagSelector);
    }

    private void _showImageSelector() {
        _createDialog("Hình ảnh", imageSelector);
    }

    private void _showPreview() {
        SuKienModel model = new SuKienModel();
        model.setTitle(title.getText());
        model.setTags(tagSelector.getSelectedTags());
        model.setContent(content.getText());
        model.setImages((ImageIcon[]) imageSelector.getSelectedImages().toArray(new ImageIcon[0]));
        model.setPostedBy(App.getSession().getUsername());
        model.setPostedAt(LocalDateTime.now());
        model.setThumbnail(imageSelector.getThumbnail());
        model.setViews(1);

        SuKienDetailScrollPane preview = new SuKienDetailScrollPane();
        try {
            preview.load(model);
        } catch (NullSuKienModelException e) {
            e.printStackTrace();
        }
        _createDialog("Xem trước bài viết", preview);
    }

    private void _createDialog(String dialogName, Component child) {
        JDialog dialog = new JDialog(App.getMainFrame(), dialogName, false);
        dialog.setLayout(new GridLayout(1, 1, 0, 0));
        dialog.setSize(child.getPreferredSize());
        dialog.add(child);
        dialog.setVisible(true);

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dialogSize = dialog.getSize();
        dialog.setLocation((screenSize.width - dialogSize.width) / 2, (screenSize.height - dialogSize.height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerPanel;
    private javax.swing.JTextArea content;
    private com.raven.scroll.ScrollPaneWin11 contentScrollPane;
    private com.uiteco.components.RoundedImagePanel imgBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private com.raven.scroll.ScrollPaneWin11 masterScrollPane;
    private com.uiteco.components.RoundedPanel masterTextPanel;
    private com.uiteco.components.RoundedPanel posterInfo;
    private com.uiteco.components.RoundedImagePanel previewBtn;
    private com.uiteco.components.RoundedImagePanel roundedImagePanel3;
    private com.uiteco.components.RoundedPanel roundedPanel1;
    private com.uiteco.components.RoundedPanel roundedPanel4;
    private com.uiteco.components.RoundedPanel roundedPanel5;
    private com.uiteco.components.RoundedImagePanel submitBtn;
    private com.uiteco.components.RoundedImagePanel tagBtn;
    private javax.swing.JTextArea title;
    private javax.swing.JLabel titleCharCountLabel;
    private com.uiteco.components.RoundedGradientPanel utilPanel;
    // End of variables declaration//GEN-END:variables
}
