/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.ofTaiKhoanPanel.createPost;

import com.uiteco.components.RoundedPanel;
import com.uiteco.ofSuKienPanel.SuKienModel;
import java.awt.Color;
import java.awt.Component;
import java.time.LocalDate;

/**
 *
 * @author nddmi
 */
public class EventSetting extends javax.swing.JPanel {

    private EventSettingSuKien eventSettingSuKien;
    private EventSettingCuocThi eventSettingCuocThi;

    private boolean initialStateChanged = false;
    private boolean enrollable;
    private Integer enrollLimit; // Nullable
    private LocalDate enrollStart; // Nullable
    private LocalDate enrollEnd; // Nullable
    private String organization; // Nullable
    private int postType = 1; // Values in (1, 2)

    /**
     * Creates new form EventSetting
     */
    public EventSetting() {
        initComponents();
        eventSettingSuKien = new EventSettingSuKien();
        eventSettingCuocThi = new EventSettingCuocThi();
        contentPanel.registerComponent(eventSettingSuKien, eventSettingSuKien.INSTANCE_NAME);
        contentPanel.registerComponent(eventSettingCuocThi, eventSettingCuocThi.INSTANCE_NAME);
    }

    public void clear() {
        suKienRadio.setSelected(true);
        cuocThiRadio.setSelected(false);
        contentPanel.showComponentAndTrimHistory(EventSettingSuKien.INSTANCE_NAME);
        eventSettingSuKien.setEnrollable(true);
        eventSettingSuKien.setEnrollLimit(null);
        eventSettingSuKien.setEnrollStart(null);
        eventSettingSuKien.setEnrollEnd(null);
    }

    public void restoreState(SuKienModel suKienModel) {
        initialStateChanged = true;

        if (suKienModel.getType() == 1) {
            suKienRadio.setSelected(true);
            cuocThiRadio.setSelected(false);
            eventSettingSuKien.setEnrollable(suKienModel.isEnrollable());
            eventSettingSuKien.setEnrollLimit(suKienModel.getEnrollLimit());
            eventSettingSuKien.setEnrollStart(suKienModel.getEnrollStart());
            eventSettingSuKien.setEnrollEnd(suKienModel.getEnrollEnd());
            contentPanel.showComponentAndTrimHistory(EventSettingSuKien.INSTANCE_NAME);

        } else if (suKienModel.getType() == 2) {
            suKienRadio.setSelected(false);
            cuocThiRadio.setSelected(true);
//            eventSettingCuocThi.setEnrollable(suKienModel.isEnrollable());
//            eventSettingCuocThi.setEnrollLimit(suKienModel.getEnrollLimit());
//            eventSettingCuocThi.setEnrollStart(suKienModel.getEnrollStart());
//            eventSettingCuocThi.setEnrollEnd(suKienModel.getEnrollEnd());
            contentPanel.showComponentAndTrimHistory(EventSettingCuocThi.INSTANCE_NAME);
        }

    }

    public boolean isEnrollable() {
        return enrollable;
    }

    public Integer getEnrollLimit() {
        return enrollLimit;
    }

    public LocalDate getEnrollStart() {
        return enrollStart;
    }

    public LocalDate getEnrollEnd() {
        return enrollEnd;
    }

    public String getOrganization() {
        return organization;
    }

    public int getPostType() {
        return postType;
    }

    public Component getCancelLabel() {
        return cancelLabel;
    }

    public Component getOkLabel() {
        return okLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGroup = new javax.swing.ButtonGroup();
        cancelBtn = new com.uiteco.components.RoundedPanel();
        cancelLabel = new javax.swing.JLabel();
        roundedGradientPanel1 = new com.uiteco.components.RoundedGradientPanel();
        roundedPanel3 = new com.uiteco.components.RoundedPanel();
        roundedImagePanel3 = new com.uiteco.components.RoundedImagePanel();
        cuocThiRadio = new javax.swing.JRadioButton();
        roundedPanel4 = new com.uiteco.components.RoundedPanel();
        roundedImagePanel4 = new com.uiteco.components.RoundedImagePanel();
        suKienRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        contentPanel = new com.uiteco.swing.ContentPanel();
        okBtn = new com.uiteco.components.RoundedPanel();
        okLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(891, 950));

        cancelBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        cancelBtn.setRoundBottomLeft(8);
        cancelBtn.setRoundBottomRight(8);
        cancelBtn.setRoundTopLeft(8);
        cancelBtn.setRoundTopRight(8);
        cancelBtn.setLayout(new java.awt.GridLayout(1, 0));

        cancelLabel.setFont(new java.awt.Font("SVN-Avo", 1, 14)); // NOI18N
        cancelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelLabel.setText("Hủy");
        cancelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelLabelMouseReleased(evt);
            }
        });
        cancelBtn.add(cancelLabel);

        roundedGradientPanel1.setColor1(new java.awt.Color(255, 255, 255));
        roundedGradientPanel1.setColor2(new java.awt.Color(183, 204, 255));
        roundedGradientPanel1.setDirection(com.uiteco.components.RoundedGradientPanel.Direction.DIAGONAL);

        roundedPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        roundedPanel3.setRoundBottomLeft(9);
        roundedPanel3.setRoundBottomRight(9);
        roundedPanel3.setRoundTopLeft(9);
        roundedPanel3.setRoundTopRight(9);
        roundedPanel3.setLayout(new java.awt.GridBagLayout());

        roundedImagePanel3.setImage(new javax.swing.ImageIcon(getClass().getResource("/uit-background.jpg"))); // NOI18N
        roundedImagePanel3.setRoundBottomLeft(11);
        roundedImagePanel3.setRoundBottomRight(11);
        roundedImagePanel3.setRoundTopLeft(11);
        roundedImagePanel3.setRoundTopRight(11);

        javax.swing.GroupLayout roundedImagePanel3Layout = new javax.swing.GroupLayout(roundedImagePanel3);
        roundedImagePanel3.setLayout(roundedImagePanel3Layout);
        roundedImagePanel3Layout.setHorizontalGroup(
            roundedImagePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roundedImagePanel3Layout.setVerticalGroup(
            roundedImagePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 15);
        roundedPanel3.add(roundedImagePanel3, gridBagConstraints);

        btnGroup.add(cuocThiRadio);
        cuocThiRadio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cuocThiRadio.setText("Cuộc thi");
        cuocThiRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuocThiRadioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        roundedPanel3.add(cuocThiRadio, gridBagConstraints);

        roundedPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 50, 30, 50));
        roundedPanel4.setRoundBottomLeft(9);
        roundedPanel4.setRoundBottomRight(9);
        roundedPanel4.setRoundTopLeft(9);
        roundedPanel4.setRoundTopRight(9);
        roundedPanel4.setLayout(new java.awt.GridBagLayout());

        roundedImagePanel4.setImage(new javax.swing.ImageIcon(getClass().getResource("/uit-background.jpg"))); // NOI18N
        roundedImagePanel4.setRoundBottomLeft(11);
        roundedImagePanel4.setRoundBottomRight(11);
        roundedImagePanel4.setRoundTopLeft(11);
        roundedImagePanel4.setRoundTopRight(11);

        javax.swing.GroupLayout roundedImagePanel4Layout = new javax.swing.GroupLayout(roundedImagePanel4);
        roundedImagePanel4.setLayout(roundedImagePanel4Layout);
        roundedImagePanel4Layout.setHorizontalGroup(
            roundedImagePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roundedImagePanel4Layout.setVerticalGroup(
            roundedImagePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 15);
        roundedPanel4.add(roundedImagePanel4, gridBagConstraints);

        btnGroup.add(suKienRadio);
        suKienRadio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        suKienRadio.setSelected(true);
        suKienRadio.setText("Sự kiện chung");
        suKienRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suKienRadioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        roundedPanel4.add(suKienRadio, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Chọn loại sự kiện và thời gian đăng ký");

        javax.swing.GroupLayout roundedGradientPanel1Layout = new javax.swing.GroupLayout(roundedGradientPanel1);
        roundedGradientPanel1.setLayout(roundedGradientPanel1Layout);
        roundedGradientPanel1Layout.setHorizontalGroup(
            roundedGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedGradientPanel1Layout.createSequentialGroup()
                        .addComponent(roundedPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        roundedGradientPanel1Layout.setVerticalGroup(
            roundedGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedGradientPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundedGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        okBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.background"));
        okBtn.setRoundBottomLeft(8);
        okBtn.setRoundBottomRight(8);
        okBtn.setRoundTopLeft(8);
        okBtn.setRoundTopRight(8);
        okBtn.setLayout(new java.awt.GridLayout(1, 0));

        okLabel.setFont(new java.awt.Font("SVN-Avo", 1, 14)); // NOI18N
        okLabel.setForeground(new java.awt.Color(255, 255, 255));
        okLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        okLabel.setText("Lưu");
        okLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                okLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okLabelMouseReleased(evt);
            }
        });
        okBtn.add(okLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(652, Short.MAX_VALUE)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(roundedGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(roundedGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(okBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void suKienRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suKienRadioActionPerformed
        // TODO add your handling code here:
        contentPanel.showComponentAndTrimHistory(EventSettingSuKien.INSTANCE_NAME);
    }//GEN-LAST:event_suKienRadioActionPerformed

    private void cuocThiRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuocThiRadioActionPerformed
        // TODO add your handling code here:
        contentPanel.showComponentAndTrimHistory(EventSettingCuocThi.INSTANCE_NAME);
    }//GEN-LAST:event_cuocThiRadioActionPerformed

    private void okLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okLabelMouseClicked
        // TODO add your handling code here:
        Component comp = contentPanel.getCurrentComponent();
        if (comp instanceof EventSettingSuKien) {
            postType = 1;
            enrollable = eventSettingSuKien.isEnrollable();
            enrollLimit = eventSettingSuKien.getEnrollLimit();
            enrollStart = eventSettingSuKien.getEnrollStart();
            enrollEnd = eventSettingSuKien.getEnrollEnd();
            initialStateChanged = true;
        } else if (comp instanceof EventSettingCuocThi) {
            // Coming soon
        }
    }//GEN-LAST:event_okLabelMouseClicked

    private void cancelLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelLabelMouseClicked
        // TODO add your handling code here:
        if (!initialStateChanged) {
//            eventSettingSuKien = new EventSettingSuKien();
//            eventSettingCuocThi = new EventSettingCuocThi();
//            contentPanel.clear();
//            contentPanel.registerComponent(eventSettingSuKien, EventSettingSuKien.INSTANCE_NAME);
//            contentPanel.registerComponent(eventSettingCuocThi, EventSettingCuocThi.INSTANCE_NAME);
        } else {
            eventSettingSuKien.setEnrollable(enrollable);
            eventSettingSuKien.setEnrollLimit(enrollLimit);
            eventSettingSuKien.setEnrollStart(enrollStart);
            eventSettingSuKien.setEnrollEnd(enrollEnd);
        }
    }//GEN-LAST:event_cancelLabelMouseClicked

    private void cancelLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelLabelMousePressed
        // TODO add your handling code here:
        cancelBtn.setForeground(new Color(61, 61, 61));
    }//GEN-LAST:event_cancelLabelMousePressed

    private void cancelLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelLabelMouseReleased
        // TODO add your handling code here:
        cancelBtn.setForeground(new Color(86, 86, 86));
    }//GEN-LAST:event_cancelLabelMouseReleased

    private void okLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okLabelMousePressed
        // TODO add your handling code here:
        okBtn.setForeground(new Color(41, 147, 255));
    }//GEN-LAST:event_okLabelMousePressed

    private void okLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okLabelMouseReleased
        // TODO add your handling code here:
        okBtn.setForeground(new Color(210, 100, 51));
    }//GEN-LAST:event_okLabelMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private com.uiteco.components.RoundedPanel cancelBtn;
    private javax.swing.JLabel cancelLabel;
    private com.uiteco.swing.ContentPanel contentPanel;
    private javax.swing.JRadioButton cuocThiRadio;
    private javax.swing.JLabel jLabel1;
    private com.uiteco.components.RoundedPanel okBtn;
    private javax.swing.JLabel okLabel;
    private com.uiteco.components.RoundedGradientPanel roundedGradientPanel1;
    private com.uiteco.components.RoundedImagePanel roundedImagePanel3;
    private com.uiteco.components.RoundedImagePanel roundedImagePanel4;
    private com.uiteco.components.RoundedPanel roundedPanel3;
    private com.uiteco.components.RoundedPanel roundedPanel4;
    private javax.swing.JRadioButton suKienRadio;
    // End of variables declaration//GEN-END:variables
}
