/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.OfCuocThiPanel.secondPage;

/**
 *
 * @author Phan Thi Thuy Hien
 */
public class DetailedOnePost_View_new extends javax.swing.JPanel {

    /**
     * Creates new form DetailedOnePost_View_new
     */
    public DetailedOnePost_View_new() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTop = new javax.swing.JPanel();
        RegisterTimePanel = new com.uiteco.components.RoundedPanel();
        jRegisterTime1 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jBody = new javax.swing.JPanel();
        jTitle1 = new javax.swing.JLabel();
        jBelowTitle = new javax.swing.JPanel();
        iconOrganization = new javax.swing.JLabel();
        postTime = new javax.swing.JLabel();
        likeButton = new com.uiteco.OfCuocThiPanel.secondPage.CustomButton();
        bookmarkButton = new com.uiteco.OfCuocThiPanel.secondPage.CustomButton();
        registerButton = new com.uiteco.OfCuocThiPanel.secondPage.CustomButton();
        like = new javax.swing.JLabel();
        register = new javax.swing.JLabel();
        bookmark = new javax.swing.JLabel();
        organizerName = new javax.swing.JLabel();
        jContent = new javax.swing.JTextArea();
        roundedPanel2 = new com.uiteco.components.RoundedPanel();

        setBackground(new java.awt.Color(204, 255, 204));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jTop.setBackground(new java.awt.Color(255, 153, 153));
        jTop.setPreferredSize(new java.awt.Dimension(1190, 370));
        jTop.setLayout(new java.awt.GridBagLayout());

        RegisterTimePanel.setPreferredSize(new java.awt.Dimension(850, 100));
        RegisterTimePanel.setRoundBottomLeft(50);
        RegisterTimePanel.setRoundBottomRight(50);
        RegisterTimePanel.setRoundTopLeft(50);
        RegisterTimePanel.setRoundTopRight(50);
        RegisterTimePanel.setLayout(new java.awt.GridBagLayout());

        jRegisterTime1.setFont(new java.awt.Font("Merriweather", 1, 34)); // NOI18N
        jRegisterTime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRegisterTime1.setText("<code>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(36, 405, 32, 401);
        RegisterTimePanel.add(jRegisterTime1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.025;
        gridBagConstraints.insets = new java.awt.Insets(0, 150, 0, 150);
        jTop.add(RegisterTimePanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(jTop, gridBagConstraints);

        jScrollPane.setBackground(new java.awt.Color(242, 243, 244));
        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setPreferredSize(new java.awt.Dimension(1190, 630));

        jBody.setBackground(new java.awt.Color(102, 255, 102));
        jBody.setOpaque(false);
        jBody.setLayout(new java.awt.GridBagLayout());

        jTitle1.setFont(new java.awt.Font("Merriweather", 1, 32)); // NOI18N
        jTitle1.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 40, 0);
        jBody.add(jTitle1, gridBagConstraints);

        jBelowTitle.setBackground(new java.awt.Color(242, 243, 244));
        jBelowTitle.setOpaque(false);
        jBelowTitle.setPreferredSize(new java.awt.Dimension(1160, 100));
        jBelowTitle.setLayout(new java.awt.GridBagLayout());

        iconOrganization.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2_files/icons8-company-64.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        jBelowTitle.add(iconOrganization, gridBagConstraints);

        postTime.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(13, 30, 20, 30);
        jBelowTitle.add(postTime, gridBagConstraints);

        likeButton.setBackground(new java.awt.Color(242, 243, 244));
        likeButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        likeButton.setText("LIKE");
        likeButton.setFont(new java.awt.Font("Merriweather", 1, 18)); // NOI18N
        likeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 40);
        jBelowTitle.add(likeButton, gridBagConstraints);

        bookmarkButton.setBackground(new java.awt.Color(242, 243, 244));
        bookmarkButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bookmarkButton.setText("BOOKMARK");
        bookmarkButton.setFont(new java.awt.Font("Merriweather", 1, 18)); // NOI18N
        bookmarkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookmarkButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 40);
        jBelowTitle.add(bookmarkButton, gridBagConstraints);

        registerButton.setBackground(new java.awt.Color(242, 243, 244));
        registerButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 0, 1, 1));
        registerButton.setText("ĐĂNG KÍ");
        registerButton.setFont(new java.awt.Font("Merriweather", 1, 18)); // NOI18N
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 40);
        jBelowTitle.add(registerButton, gridBagConstraints);

        like.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2_files/icons8-like-50.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jBelowTitle.add(like, gridBagConstraints);

        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2_files/edit_10969571.png"))); // NOI18N
        register.setMaximumSize(new java.awt.Dimension(50, 50));
        register.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 10);
        jBelowTitle.add(register, gridBagConstraints);

        bookmark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2_files/bookmark_10969413.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        jBelowTitle.add(bookmark, gridBagConstraints);

        organizerName.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(23, 30, 9, 30);
        jBelowTitle.add(organizerName, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(32, 135, 60, 88);
        jBody.add(jBelowTitle, gridBagConstraints);

        jContent.setEditable(false);
        jContent.setColumns(20);
        jContent.setFont(new java.awt.Font("Merriweather", 0, 24)); // NOI18N
        jContent.setLineWrap(true);
        jContent.setWrapStyleWord(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 204, 50, 167);
        jBody.add(jContent, gridBagConstraints);

        roundedPanel2.setBackground(new java.awt.Color(204, 255, 51));

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 39, 0, 39);
        jBody.add(roundedPanel2, gridBagConstraints);

        jScrollPane.setViewportView(jBody);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 11.0;
        add(jScrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    private void bookmarkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookmarkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookmarkButtonActionPerformed

    private void likeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_likeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.uiteco.components.RoundedPanel RegisterTimePanel;
    private javax.swing.JLabel bookmark;
    private com.uiteco.OfCuocThiPanel.secondPage.CustomButton bookmarkButton;
    private javax.swing.JLabel iconOrganization;
    private javax.swing.JPanel jBelowTitle;
    private javax.swing.JPanel jBody;
    private javax.swing.JTextArea jContent;
    private javax.swing.JLabel jRegisterTime1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel jTitle1;
    private javax.swing.JPanel jTop;
    private javax.swing.JLabel like;
    private com.uiteco.OfCuocThiPanel.secondPage.CustomButton likeButton;
    private javax.swing.JLabel organizerName;
    private javax.swing.JLabel postTime;
    private javax.swing.JLabel register;
    private com.uiteco.OfCuocThiPanel.secondPage.CustomButton registerButton;
    private com.uiteco.components.RoundedPanel roundedPanel2;
    // End of variables declaration//GEN-END:variables
}
