/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.ofSuKienPanel.detailed.rightPanel;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.uiteco.components.GradientPanel;
import com.uiteco.ofSuKienPanel.SuKienModel;
import com.uiteco.ofTaiKhoanPanel.TaiKhoanModel;
import java.awt.Color;
import java.time.format.DateTimeFormatter;
import net.miginfocom.swing.MigLayout;
import com.uiteco.ofSuKienPanel.SuKienDAO;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.LinkedList;
import static com.uiteco.main.App.getSession;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author nddmi
 */
public class ParticipantsPanel extends GradientPanel {

    private boolean userEnrolled;
    private Integer myEnrollIndex;

    private boolean isEarly;
    private boolean isLate;
    private SuKienModel suKienModel;
    DateTimeFormatter dateFmt = DateTimeFormatter.ofPattern("dd/MM/yy");
    LinkedList<TaiKhoanModel> participants;

    private Color earlyButtonColor = new Color(229, 229, 229);
    private Color lateButtonColor = Color.RED;
    private Color normalButtonColor = new Color(10, 132, 255);
    private Color normalButtonPressColor = new Color(41, 147, 255);
    private Color normalButtonHoverColor = new Color(25, 140, 255);

    private Color earlyLabelColor = new Color(171, 171, 171);
    private Color lateLabelColor = Color.DARK_GRAY;
    private Color normalLabelColor = Color.WHITE;
    private Color normalLabelPressColor = Color.WHITE;
    private Color normalLabelHoverColor = Color.WHITE;

    private Color enrolledButtonColor = new Color(11, 244, 70);
    private Color enrolledButtonHoverColor = new Color(0, 204, 51);
    private Color enrolledButtonPressColor = new Color(4, 161, 43);

    /**
     * Creates new form ParticipantsPanel
     */
    public ParticipantsPanel(SuKienModel suKienModel) {
        FlatMacLightLaf.setup();
        this.suKienModel = suKienModel;

        LocalDate today = LocalDate.now();
        isEarly = today.isBefore(suKienModel.getEnrollStart());
        isLate = today.isAfter(suKienModel.getEnrollEnd());

        initComponents();
//        setColor1(new Color(210, 217, 231));
//        setColor2(new Color(157, 162, 195));
        setColor1(new Color(255, 254, 252));
        setColor2(new Color(204, 227, 232));
        setDirection(Direction.DIAGONAL);
        _populateParticipantList();

        if (userEnrolled) {
            jLabel13.setText("Đã ghi danh");
            jLabel13.setIcon(new ImageIcon(getClass().getResource("/icons8-tick-24.png")));
            button.setBackground(enrolledButtonColor);
            jLabel13.setForeground(normalLabelColor);

        } else if (isEarly) {
            button.setBackground(earlyButtonColor);
            jLabel13.setForeground(earlyLabelColor);
        } else if (isLate) {
            button.setBackground(lateButtonColor);
            jLabel13.setForeground(lateLabelColor);
        } else {
            button.setBackground(normalButtonColor);
            button.setForeground(normalLabelColor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new com.uiteco.components.RoundedPanel();
        roundedImagePanel1 = new com.uiteco.components.RoundedImagePanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        scrollPaneWin111 = new com.raven.scroll.ScrollPaneWin11();
        viewport = new javax.swing.JPanel();
        roundedPanel2 = new com.uiteco.components.RoundedPanel();
        jLabel12 = new javax.swing.JLabel();
        button = new com.uiteco.components.RoundedPanel();
        jLabel13 = new javax.swing.JLabel();

        roundedPanel1.setRoundBottomLeft(40);
        roundedPanel1.setRoundBottomRight(40);
        roundedPanel1.setRoundTopLeft(40);
        roundedPanel1.setRoundTopRight(40);

        roundedImagePanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedImagePanel1.setImage(suKienModel.getThumbnail());
        roundedImagePanel1.setRoundBottomLeft(12);
        roundedImagePanel1.setRoundBottomRight(12);
        roundedImagePanel1.setRoundTopLeft(12);
        roundedImagePanel1.setRoundTopRight(12);

        javax.swing.GroupLayout roundedImagePanel1Layout = new javax.swing.GroupLayout(roundedImagePanel1);
        roundedImagePanel1.setLayout(roundedImagePanel1Layout);
        roundedImagePanel1Layout.setHorizontalGroup(
            roundedImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roundedImagePanel1Layout.setVerticalGroup(
            roundedImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("SVN-Avo", 1, 16)); // NOI18N
        jLabel1.setText("Thời hạn đăng ký");

        jLabel3.setFont(new java.awt.Font("SVN-Avo", 1, 16)); // NOI18N
        jLabel3.setText("Sỉ số:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText(String.valueOf(suKienModel.getEnrollCount()));

        Integer limit = suKienModel.getEnrollLimit();
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("/" + String.valueOf(limit));
        if (limit == null) {
            jLabel4.setVisible(false);
        }

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("(Sự kiện không giới hạn số lượt đăng ký tham gia)");
        if (suKienModel.getEnrollLimit() != null) {
            jLabel6.setVisible(false);
        }

        jSeparator1.setForeground(new java.awt.Color(227, 191, 237));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText(suKienModel.getTitle());

        String toDate = suKienModel.getEnrollEnd().format(dateFmt);
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText(toDate);

        String fromDate = suKienModel.getEnrollStart().format(dateFmt);
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setText(fromDate);

        jLabel10.setFont(new java.awt.Font("SVN-Avo", 1, 14)); // NOI18N
        jLabel10.setText("Từ ngày:");

        jLabel11.setFont(new java.awt.Font("SVN-Avo", 1, 14)); // NOI18N
        jLabel11.setText("Đến ngày:");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedImagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jLabel6))
                        .addGap(89, 89, 89)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(roundedImagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)))
                                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("THAM GIA SỰ KIỆN");

        scrollPaneWin111.setBorder(null);

        viewport.setForeground(new java.awt.Color(242, 243, 244));
        viewport.setOpaque(false);

        javax.swing.GroupLayout viewportLayout = new javax.swing.GroupLayout(viewport);
        viewport.setLayout(viewportLayout);
        viewportLayout.setHorizontalGroup(
            viewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
        );
        viewportLayout.setVerticalGroup(
            viewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        String migConstraint = "wrap 1, gapx 10, gapy 10, insets 0 20 0 20";
        viewport.setLayout(new MigLayout(migConstraint));

        scrollPaneWin111.setViewportView(viewport);

        roundedPanel2.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        roundedPanel2.setRoundBottomLeft(12);
        roundedPanel2.setRoundBottomRight(33);
        roundedPanel2.setRoundTopLeft(12);
        roundedPanel2.setRoundTopRight(33);
        roundedPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel12.setFont(new java.awt.Font("SVN-Avo", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(5, 5, 5));
        jLabel12.setText("Danh sách đăng ký tham gia");
        roundedPanel2.add(jLabel12);

        button.setBackground(normalButtonColor);
        button.setRoundBottomLeft(12);
        button.setRoundBottomRight(12);
        button.setRoundTopLeft(12);
        button.setRoundTopRight(12);
        button.setLayout(new java.awt.GridLayout(1, 0));

        jLabel13.setFont(new java.awt.Font("SVN-Avo", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Ghi danh");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        button.add(jLabel13);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
        if (userEnrolled) {
            button.setBackground(enrolledButtonHoverColor);
            jLabel13.setForeground(normalLabelHoverColor);
        } else if (!isEarly && !isLate) {
            button.setBackground(normalButtonHoverColor);
            jLabel13.setForeground(normalLabelHoverColor);
        }
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
        if (userEnrolled) {
            button.setBackground(enrolledButtonColor);
            jLabel13.setForeground(normalLabelColor);
        } else if (!isEarly && !isLate) {
            button.setBackground(normalButtonColor);
            jLabel13.setForeground(normalLabelColor);
        }
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        if (userEnrolled) {
            button.setBackground(enrolledButtonPressColor);
            jLabel13.setForeground(normalLabelPressColor);
            int option = JOptionPane.showOptionDialog(this, "Bạn đã đăng ký tham gia, bạn có muốn hủy đăng ký", "Xác nhận", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (option == JOptionPane.YES_OPTION) {
                _unEnrollInSuKien();
            }
        } else if (isEarly) {
//            JOptionPane.showMessageDialog(this, "Sự kiện chưa mở cổng đăng ký", "Không thể đăng ký sự kiện", JOptionPane.WARNING_MESSAGE);
            ImageIcon icon = new ImageIcon(getClass().getResource("/icons8-email-48.png"));
            int option = JOptionPane.showOptionDialog(this, "Bạn có muốn nhận thông báo qua email khi sự kiện mở cổng đăng ký?", "Sự kiện chưa đến thời điểm đăng ký", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, icon, null, 0);
            if (option == JOptionPane.YES_NO_OPTION) {
                // Hihi, lam mau thui chu lam j con thgian de lam tinh nang gui thong bao qua email
            }
        } else if (isLate) {
            JOptionPane.showMessageDialog(this, "Sự kiện đã quá hạn đăng ký", "Không thể đăng ký sự kiện", JOptionPane.WARNING_MESSAGE);
        } else {
            button.setBackground(normalButtonPressColor);
            jLabel13.setForeground(normalLabelPressColor);
            int option = JOptionPane.showOptionDialog(this, "Bạn có chắc muốn đăng ký tham gia sự kiện?", "Xác nhận", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (option == JOptionPane.YES_OPTION) {
                _enrollInSuKien();
            }
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void _enrollInSuKien() {
        try {
            SuKienDAO.enrollInSuKien(suKienModel);
            JOptionPane.showMessageDialog(
                    this,
                    "Đăng ký thành công",
                    "Thành công",
                    JOptionPane.PLAIN_MESSAGE,
                    new ImageIcon(getClass().getResource("/icons8-tick-24.png"))
            );
            userEnrolled = true;
            jLabel13.setText("Đã ghi danh");
            jLabel13.setIcon(new ImageIcon(getClass().getResource("/icons8-tick-24.png")));
            button.setBackground(enrolledButtonColor);
            jLabel13.setForeground(normalLabelColor);
            jLabel5.setText(String.valueOf(suKienModel.getEnrollCount()));
            jLabel5.repaint();

            if (participants != null) {
                TaiKhoanModel currentUser = getSession().getUser();
                participants.add(currentUser);
                viewport.add(new ParticipantLine(currentUser, participants.size(), true), "growx");
                myEnrollIndex = viewport.getComponentCount() - 1;
                viewport.revalidate();
                viewport.repaint();
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "Đăng ký không thành công",
                    "Lỗi hệ thống",
                    JOptionPane.ERROR_MESSAGE,
                    new ImageIcon(getClass().getResource("/icons8-cross-24.png"))
            );
        }
    }

    private void _unEnrollInSuKien() {
        try {
            SuKienDAO.enrollInSuKien(suKienModel);
            userEnrolled = false;
            jLabel13.setIcon(null);
            jLabel13.setText("Ghi danh");
            button.setBackground(normalButtonColor);
            jLabel13.setForeground(normalLabelColor);
            jLabel5.setText(String.valueOf(suKienModel.getEnrollCount()));
            jLabel5.repaint();

            if (participants != null && myEnrollIndex != null) {
                participants.remove(myEnrollIndex);
                viewport.remove(myEnrollIndex);
                viewport.revalidate();
                viewport.repaint();

                int len = viewport.getComponentCount();
                for (int i = myEnrollIndex; i < len; i++) {
                    ((ParticipantLine) viewport.getComponent(i)).setOrder(i + 1);
                }
                myEnrollIndex = null;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "Hủy đăng ký không thành công",
                    "Lỗi hệ thống",
                    JOptionPane.ERROR_MESSAGE,
                    new ImageIcon(getClass().getResource("/icons8-cross-24.png"))
            );

        }
    }

    private void _populateParticipantList() {
        viewport.removeAll();
        try {
            participants = SuKienDAO.getParticipants(this.suKienModel);
            int len = participants.size();
            int thisAccountID = getSession().getUser().getAccountID();

            for (int i = 0; i < len; i++) {
                TaiKhoanModel participant = participants.get(i);
                boolean isMe = (thisAccountID == participant.getAccountID());
                if (isMe) {
                    userEnrolled = true;
                    myEnrollIndex = i;
                }
                ParticipantLine line = new ParticipantLine(participant, i + 1, isMe);
                viewport.add(line, "growx");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            viewport.revalidate();
            viewport.repaint();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.uiteco.components.RoundedPanel button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private com.uiteco.components.RoundedImagePanel roundedImagePanel1;
    private com.uiteco.components.RoundedPanel roundedPanel1;
    private com.uiteco.components.RoundedPanel roundedPanel2;
    private com.raven.scroll.ScrollPaneWin11 scrollPaneWin111;
    private javax.swing.JPanel viewport;
    // End of variables declaration//GEN-END:variables
}
