/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.ofSuKienPanel.detailed.rightPanel;

import com.uiteco.components.GradientPanel;
import com.uiteco.ofSuKienPanel.SuKienDAO;
import com.uiteco.ofSuKienPanel.SuKienModel;
import com.uiteco.ofTaiKhoanPanel.TaiKhoanModel;
import java.awt.Color;
import java.util.ArrayList;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author nddmi
 */
public class SuKienDetailRightPanel extends GradientPanel {

    public static final String INSTANCE_NAME = "suKienDetailRightPanel";

    /**
     * Creates new form DetailedRightPanel
     */
    public SuKienDetailRightPanel() {
        initComponents();
//        setColor1((new Color(168, 202, 240)).brighter());
//        setColor2((new Color(236, 243, 251)).brighter());
        setDirection(GradientPanel.DIAGONAL);
        likesPanel.setLayout(new MigLayout("fillx, debug", "[grow]", "[]10[]"));
    }

    public void load(SuKienModel suKienModel) {
        try {
            likesPanel.removeAll();
            ArrayList<TaiKhoanModel> list = SuKienDAO.getLikers(suKienModel);
            if (list.size() < 1) {
                likesPanel.revalidate();
                likesPanel.repaint();
                return;
            }
            for (TaiKhoanModel m : list) {
                LikerLine v = new LikerLine(m);
//                likesPanel.add(v, "growx, wrap, width ::" + likesPanel.getPreferredSize().width);
                likesPanel.add(v, "growx, wrap");
            }
            likesPanel.revalidate();
            likesPanel.repaint();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        likeLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        likeScrollPane = new com.raven.scroll.ScrollPaneWin11();
        likesPanel = new javax.swing.JPanel();
        dateChooser2 = new com.raven.datechooser.DateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setColor1(java.awt.Color.white);
        setColor2(new java.awt.Color(255, 255, 255));
        setDirection(com.uiteco.components.GradientPanel.Direction.HORIZONTAL);
        setFade(false);
        setLayout(new java.awt.GridBagLayout());

        likeLabel.setBackground(new java.awt.Color(153, 255, 153));
        likeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        likeLabel.setForeground(new java.awt.Color(0, 204, 0));
        likeLabel.setText("Lượt thích");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 5, 0);
        add(likeLabel, gridBagConstraints);

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        add(jSeparator1, gridBagConstraints);

        likeScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        likesPanel.setBackground(new java.awt.Color(255, 255, 255));
        likesPanel.setPreferredSize(new java.awt.Dimension(400, 603));

        javax.swing.GroupLayout likesPanelLayout = new javax.swing.GroupLayout(likesPanel);
        likesPanel.setLayout(likesPanelLayout);
        likesPanelLayout.setHorizontalGroup(
            likesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );
        likesPanelLayout.setVerticalGroup(
            likesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );

        likeScrollPane.setViewportView(likesPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(likeScrollPane, gridBagConstraints);

        dateChooser2.setForeground(new java.awt.Color(90, 207, 241));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        add(dateChooser2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.datechooser.DateChooser dateChooser2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel likeLabel;
    private com.raven.scroll.ScrollPaneWin11 likeScrollPane;
    private javax.swing.JPanel likesPanel;
    // End of variables declaration//GEN-END:variables
}
