/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.ofSuKienRightPanel;

import com.uiteco.components.RoundedGradientPanel;
import com.uiteco.ofSuKienPanel.SuKienModel;
import java.awt.Dimension;
import java.util.Queue;
import java.util.LinkedList;
import java.util.List;
import javax.swing.Box;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author nddmi
 */
public class HistoryPanel extends javax.swing.JPanel {

    public static final int MAX_HISTORY_ENTRIES = 20;
    protected int historySize;

    /**
     * Creates new form HistoryPanel
     */
    public HistoryPanel() {
        initComponents();
        textContainer.setLayout(new MigLayout("fillx, wrap"));
        historySize = 0;
    }

    public void addHistory(SuKienModel suKienModel) {
        // Skip duplicate

        if (textContainer.getComponentCount() > 0
                && ((HistoryTextLine) textContainer.getComponent(0)).getSuKienModel().equals(suKienModel)) {
            return;
        }

        if (historySize >= MAX_HISTORY_ENTRIES) {
//            history.removeFirst(); // Trim head bcuz head is oldest and tail is most-recent
            textContainer.remove(historySize - 1);
            historySize = 0;
            revalidate();
            repaint();
        }

        textContainer.add(new HistoryTextLine(suKienModel), 0);
        historySize++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        textContainer = new com.uiteco.components.RoundedGradientPanel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-history-24.png"))); // NOI18N
        jLabel1.setLabelFor(textContainer);
        jLabel1.setText("Lịch sử");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 15);
        add(jLabel1, gridBagConstraints);

        textContainer.setColor1(new java.awt.Color(235, 88, 111));
        textContainer.setRoundBottomLeft(20);
        textContainer.setRoundBottomRight(20);
        textContainer.setRoundTopLeft(20);
        textContainer.setRoundTopRight(20);

        javax.swing.GroupLayout textContainerLayout = new javax.swing.GroupLayout(textContainer);
        textContainer.setLayout(textContainerLayout);
        textContainerLayout.setHorizontalGroup(
            textContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        textContainerLayout.setVerticalGroup(
            textContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 20, 15);
        add(textContainer, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-cross-24.png"))); // NOI18N
        jLabel2.setText("Xóa");
        jLabel2.setToolTipText("Xóa lịch sử");
        jLabel2.setDoubleBuffered(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 20);
        add(jLabel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel2.setForeground(jLabel2.getForeground().darker());
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel2.setForeground(jLabel2.getForeground().brighter());
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        textContainer.removeAll();
        historySize = 0;
        textContainer.revalidate();
        textContainer.repaint();
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.uiteco.components.RoundedGradientPanel textContainer;
    // End of variables declaration//GEN-END:variables
}
