/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.ofSuKienRightPanel;

import com.uiteco.components.RoundedGradientPanel;
import com.uiteco.ofSuKienPanel.SuKienModel;
import java.awt.Dimension;
import java.util.Queue;
import java.util.LinkedList;
import java.util.List;
import javax.swing.Box;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author nddmi
 */
public class HistoryPanel extends javax.swing.JPanel {
    public static final int MAX_HISTORY_ENTRIES = 20;
    protected LinkedList<SuKienModel> history;
    
    /**
     * Creates new form HistoryPanel
     */
    public HistoryPanel() {
        initComponents();
        history = new LinkedList<SuKienModel>();
        textContainer.setLayout(new MigLayout("fillx, wrap"));
        
    }
    
    public LinkedList<SuKienModel> getHistory() {
        return this.history;
    }
    
    
    public void setHistory(LinkedList<SuKienModel> history) {
        this.history = history;
    }
    
    public void addHistory(SuKienModel suKienModel) {
        if (history.size() >= MAX_HISTORY_ENTRIES) {
            history.removeFirst(); // Trim head bcuz head is oldest and tail is most-recent
        }
        history.add(suKienModel);
        _populateHistoryLines();
    }
    
    protected void _populateHistoryLines() {
        textContainer.removeAll();
        for (SuKienModel suKienModel : history) {
            textContainer.add(new HistoryTextLine(suKienModel.getThumbnail(), suKienModel.getTitle()), "span");
        }
        textContainer.revalidate();
        textContainer.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        textContainer = new com.uiteco.components.RoundedGradientPanel();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-history-24.png"))); // NOI18N
        jLabel1.setLabelFor(textContainer);
        jLabel1.setText("Lịch sử");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 10, 15);
        add(jLabel1, gridBagConstraints);

        textContainer.setColor1(new java.awt.Color(235, 88, 111));
        textContainer.setRoundBottomLeft(20);
        textContainer.setRoundBottomRight(20);
        textContainer.setRoundTopLeft(20);
        textContainer.setRoundTopRight(20);

        javax.swing.GroupLayout textContainerLayout = new javax.swing.GroupLayout(textContainer);
        textContainer.setLayout(textContainerLayout);
        textContainerLayout.setHorizontalGroup(
            textContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        textContainerLayout.setVerticalGroup(
            textContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 20, 30);
        add(textContainer, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private com.uiteco.components.RoundedGradientPanel textContainer;
    // End of variables declaration//GEN-END:variables
}
