/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.ofTaiKhoanPanel.postManagement;

import com.uiteco.components.RoundedImagePanel;
import com.uiteco.components.RoundedPanel;
import static com.uiteco.ofSuKienPanel.SuKienDAO.deletePost;
import com.uiteco.ofSuKienPanel.SuKienModel;
import java.awt.Component;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author nddmi
 */
public class PostLine extends RoundedPanel {

    SuKienModel suKienModel;
    DateTimeFormatter dateFmt = DateTimeFormatter.ofPattern("dd.MM.yy");
    DateTimeFormatter timeFmt = DateTimeFormatter.ofPattern("HH:mm");

    /**
     * Creates new form PostLine
     */
    public PostLine(SuKienModel suKienModel) {
        this.suKienModel = suKienModel;
        initComponents();
        setRoundTopLeft(22);
        setRoundTopRight(22);
        setRoundBottomLeft(22);
        setRoundBottomRight(22);
    }

    public RoundedImagePanel getDelBtn() {
        return delBtn;
    }

    public RoundedImagePanel getEditBtn() {
        return editBtn;
    }

    public RoundedImagePanel getParticipantsBtn() {
        return participantsBtn;
    }

    public SuKienModel getSuKienModel() {
        return suKienModel;
    }
    
    public Component getTitleLabel() {
        return title;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        postedAt = new javax.swing.JLabel();
        views = new javax.swing.JLabel();
        likes = new javax.swing.JLabel();
        roundedPanel1 = new com.uiteco.components.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        postID = new javax.swing.JLabel();
        participantsBtn = new com.uiteco.components.RoundedImagePanel();
        editBtn = new com.uiteco.components.RoundedImagePanel();
        delBtn = new com.uiteco.components.RoundedImagePanel();
        jSeparator1 = new javax.swing.JSeparator();
        roundedImagePanel7 = new com.uiteco.components.RoundedImagePanel();
        postedAt1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 5));
        setPreferredSize(null);

        title.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        title.setForeground(new java.awt.Color(5, 5, 5));
        title.setText(suKienModel.getTitle());

        String date = suKienModel.getPostedAt().format(this.dateFmt);
        String time = suKienModel.getPostedAt().format(this.timeFmt);
        postedAt.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        postedAt.setForeground(new java.awt.Color(102, 102, 102));
        postedAt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-up-24.png"))); // NOI18N
        postedAt.setText(date + " - " + time);
        postedAt.setToolTipText("Đăng lần đầu");

        views.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        views.setForeground(new java.awt.Color(102, 102, 102));
        views.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-eye-30.png"))); // NOI18N
        views.setText(String.valueOf(suKienModel.getViews()));

        likes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        likes.setForeground(new java.awt.Color(102, 102, 102));
        likes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-heart-30.png"))); // NOI18N
        likes.setText(String.valueOf(suKienModel.getLikes()));

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 204));
        roundedPanel1.setRoundBottomLeft(33);
        roundedPanel1.setRoundBottomRight(12);
        roundedPanel1.setRoundTopLeft(12);
        roundedPanel1.setRoundTopRight(12);
        roundedPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mã bđ");
        roundedPanel1.add(jLabel1);

        postID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        postID.setForeground(new java.awt.Color(153, 153, 153));
        postID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        postID.setText(String.valueOf(suKienModel.getPostID()));
        roundedPanel1.add(postID);

        participantsBtn.setToolTipText("Quản lý sinh viên tham gia");
        participantsBtn.setImage(new javax.swing.ImageIcon(getClass().getResource("/icons8-conference-33.png"))); // NOI18N
        participantsBtn.setInheritsPopupMenu(true);
        participantsBtn.setPreferredSize(new java.awt.Dimension(28, 28));
        participantsBtn.setRoundBottomLeft(44);
        participantsBtn.setRoundBottomRight(44);
        participantsBtn.setRoundTopLeft(44);
        participantsBtn.setRoundTopRight(44);

        javax.swing.GroupLayout participantsBtnLayout = new javax.swing.GroupLayout(participantsBtn);
        participantsBtn.setLayout(participantsBtnLayout);
        participantsBtnLayout.setHorizontalGroup(
            participantsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        participantsBtnLayout.setVerticalGroup(
            participantsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        editBtn.setToolTipText("Chỉnh sửa");
        editBtn.setImage(new javax.swing.ImageIcon(getClass().getResource("/icons8-edit-33.png"))); // NOI18N
        editBtn.setInheritsPopupMenu(true);
        editBtn.setPreferredSize(new java.awt.Dimension(28, 28));
        editBtn.setRoundBottomLeft(44);
        editBtn.setRoundBottomRight(44);
        editBtn.setRoundTopLeft(44);
        editBtn.setRoundTopRight(44);

        javax.swing.GroupLayout editBtnLayout = new javax.swing.GroupLayout(editBtn);
        editBtn.setLayout(editBtnLayout);
        editBtnLayout.setHorizontalGroup(
            editBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        editBtnLayout.setVerticalGroup(
            editBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        delBtn.setToolTipText("Xóa bài viết");
        delBtn.setImage(new javax.swing.ImageIcon(getClass().getResource("/icons8-trash-30.png"))); // NOI18N
        delBtn.setInheritsPopupMenu(true);
        delBtn.setPreferredSize(new java.awt.Dimension(28, 28));
        delBtn.setRoundBottomLeft(44);
        delBtn.setRoundBottomRight(44);
        delBtn.setRoundTopLeft(44);
        delBtn.setRoundTopRight(44);
        delBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout delBtnLayout = new javax.swing.GroupLayout(delBtn);
        delBtn.setLayout(delBtnLayout);
        delBtnLayout.setHorizontalGroup(
            delBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        delBtnLayout.setVerticalGroup(
            delBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSeparator1.setForeground(new java.awt.Color(255, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        roundedImagePanel7.setToolTipText("Quản lý sinh viên tham gia");
        roundedImagePanel7.setImage(suKienModel.getThumbnail());
        roundedImagePanel7.setInheritsPopupMenu(true);
        roundedImagePanel7.setPreferredSize(new java.awt.Dimension(28, 28));
        roundedImagePanel7.setRoundBottomLeft(25);
        roundedImagePanel7.setRoundBottomRight(25);
        roundedImagePanel7.setRoundTopLeft(25);
        roundedImagePanel7.setRoundTopRight(25);

        javax.swing.GroupLayout roundedImagePanel7Layout = new javax.swing.GroupLayout(roundedImagePanel7);
        roundedImagePanel7.setLayout(roundedImagePanel7Layout);
        roundedImagePanel7Layout.setHorizontalGroup(
            roundedImagePanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roundedImagePanel7Layout.setVerticalGroup(
            roundedImagePanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        postedAt1.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        postedAt1.setForeground(new java.awt.Color(102, 102, 102));
        String updateDate = suKienModel.getLastUpdated().format(this.dateFmt);
        String updateTime = suKienModel.getLastUpdated().format(this.timeFmt);
        postedAt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-edit-24.png"))); // NOI18N
        postedAt1.setText(updateDate + " - " + updateTime);
        postedAt1.setToolTipText("Lần cuối chỉnh sửa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundedImagePanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(views)
                            .addComponent(postedAt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(postedAt1)
                            .addComponent(likes))))
                .addGap(332, 332, 332)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(participantsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedImagePanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(postedAt)
                                    .addComponent(postedAt1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(views)
                                    .addComponent(likes))
                                .addGap(0, 3, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(participantsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void delBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_delBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.uiteco.components.RoundedImagePanel delBtn;
    private com.uiteco.components.RoundedImagePanel editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel likes;
    private com.uiteco.components.RoundedImagePanel participantsBtn;
    private javax.swing.JLabel postID;
    private javax.swing.JLabel postedAt;
    private javax.swing.JLabel postedAt1;
    private com.uiteco.components.RoundedImagePanel roundedImagePanel3;
    private com.uiteco.components.RoundedImagePanel roundedImagePanel4;
    private com.uiteco.components.RoundedImagePanel roundedImagePanel7;
    private com.uiteco.components.RoundedPanel roundedPanel1;
    private javax.swing.JLabel title;
    private javax.swing.JLabel views;
    // End of variables declaration//GEN-END:variables
}
