/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.ofTaiKhoanPanel.ofClbPanel;

import com.uiteco.components.RoundedPanel;
import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author nddmi
 */
public class Clb extends RoundedPanel {

    public static class MiniClbModel {
        private Icon clbAvatar;
        private String clbName;
        private String clbRole;
        private String personName;

        public Icon getClbAvatar() {
            return clbAvatar;
        }

        public String getClbName() {
            return clbName;
        }

        public String getClbRole() {
            return clbRole;
        }

        public String getPersonName() {
            return personName;
        }

        public void setClbAvatar(Icon clbAvatar) {
            this.clbAvatar = clbAvatar;
        }

        public void setClbName(String clbName) {
            this.clbName = clbName;
        }

        public void setClbRole(String clbRole) {
            this.clbRole = clbRole;
        }

        public void setPersonName(String personName) {
            this.personName = personName;
        }
    }
    
    private MiniClbModel model;

    public Clb(MiniClbModel model) {
        setModel(model);
        initComponents();
    }

    public Clb() {
    }
    
    public MiniClbModel getModel() {
        return this.model;
    }
    
    public void setModel(MiniClbModel model) {
        this.model = model;
    }
    
    private void _showClbDetailPage() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        clbAvatarPanel = new com.uiteco.components.RoundedImagePanel();
        clbNameTxt = new javax.swing.JLabel();
        personNameTxt = new javax.swing.JLabel();
        clbRoleText = new javax.swing.JLabel();
        roundedGradientPanel1 = new com.uiteco.components.RoundedGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 210));
        setRoundBottomLeft(33);
        setRoundBottomRight(33);
        setRoundTopLeft(33);
        setRoundTopRight(33);
        setLayout(new java.awt.GridBagLayout());

        clbAvatarPanel.setImage(new javax.swing.ImageIcon(getClass().getResource("/OEC.jpg"))); // NOI18N
        clbAvatarPanel.setPreferredSize(new java.awt.Dimension(130, 130));
        clbAvatarPanel.setRoundBottomLeft(35);
        clbAvatarPanel.setRoundBottomRight(35);
        clbAvatarPanel.setRoundTopLeft(35);
        clbAvatarPanel.setRoundTopRight(35);

        javax.swing.GroupLayout clbAvatarPanelLayout = new javax.swing.GroupLayout(clbAvatarPanel);
        clbAvatarPanel.setLayout(clbAvatarPanelLayout);
        clbAvatarPanelLayout.setHorizontalGroup(
            clbAvatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        clbAvatarPanelLayout.setVerticalGroup(
            clbAvatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        add(clbAvatarPanel, gridBagConstraints);

        clbNameTxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        clbNameTxt.setForeground(new java.awt.Color(83, 83, 83));
        clbNameTxt.setText(this.model.getClbName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(clbNameTxt, gridBagConstraints);

        personNameTxt.setFont(new java.awt.Font("Segoe UI Variable", 1, 15)); // NOI18N
        personNameTxt.setForeground(new java.awt.Color(129, 133, 139));
        personNameTxt.setText(model.getPersonName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(30, 15, 0, 15);
        add(personNameTxt, gridBagConstraints);

        clbRoleText.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        clbRoleText.setText(model.getClbRole());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        add(clbRoleText, gridBagConstraints);

        roundedGradientPanel1.setBorder(null);
        roundedGradientPanel1.setColor1(new java.awt.Color(235, 245, 255));
        roundedGradientPanel1.setColor2(new java.awt.Color(235, 245, 255));
        roundedGradientPanel1.setPreferredSize(new java.awt.Dimension(100, 40));
        roundedGradientPanel1.setRoundBottomLeft(25);
        roundedGradientPanel1.setRoundBottomRight(25);
        roundedGradientPanel1.setRoundTopLeft(25);
        roundedGradientPanel1.setRoundTopRight(25);
        roundedGradientPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(129, 133, 139));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Xem CLB");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        roundedGradientPanel1.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        add(roundedGradientPanel1, gridBagConstraints);

        jSeparator1.setForeground(java.awt.SystemColor.inactiveCaption);
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        add(jSeparator1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        roundedGradientPanel1.setColor1(roundedGradientPanel1.getColor1().brighter());
        roundedGradientPanel1.setColor2(roundedGradientPanel1.getColor2().brighter());
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        roundedGradientPanel1.setColor1(new Color(235, 245, 255));
        roundedGradientPanel1.setColor2(new Color(235, 245, 255));
    }//GEN-LAST:event_jLabel1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.uiteco.components.RoundedImagePanel clbAvatarPanel;
    private javax.swing.JLabel clbNameTxt;
    private javax.swing.JLabel clbRoleText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel personNameTxt;
    private com.uiteco.components.RoundedGradientPanel roundedGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
