/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.ofTaiKhoanPanel;

/**
 *
 * @author nddmi
 */
public class HoatDongPanel extends javax.swing.JPanel {
    public static final String INSTANCE_NAME = "hoatDongPanel";
    TaiKhoanModel user;
    /**
     * Creates new form HoatDongPanel
     */
    public HoatDongPanel() {
    }

    public void load(TaiKhoanModel user) {
        this.user = user;
        removeAll();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        loginActivity1 = new com.uiteco.ofTaiKhoanPanel.ofHoatDongPanel.LoginActivity(this.user);

        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setPreferredSize(new java.awt.Dimension(260, 200));
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 0.2;
        add(loginActivity1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.uiteco.ofTaiKhoanPanel.ofHoatDongPanel.LoginActivity loginActivity1;
    // End of variables declaration//GEN-END:variables
}
