/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.OfCuocThiPanel.firstPage.slideShow;

import com.uiteco.OfCuocThiPanel.dataBase.CuocThiDAO;
import com.uiteco.components.RoundedImagePanel;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Phan Thi Thuy Hien
 */
public class NewestCompetitions_new extends javax.swing.JPanel {

    /**
     * Creates new form NewestCompetitions_new
     */
    public NewestCompetitions_new() {
        
        initComponents();
        List<ImageIcon> imageList = CuocThiDAO.getImagesForSlideshow();
        List<Component> list = new ArrayList<>();
        for(ImageIcon image : imageList){
            
            RoundedImagePanel r = new RoundedImagePanel();
            r.setImage(image);
            r.setRoundBottomLeft(30);
            r.setRoundBottomRight(30);
            r.setRoundTopLeft(30);
            r.setRoundTopRight(30);
            
            list.add(r);
        }
        
        slideShow_AutoSlide.initSlideshow(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        roundedGradientPanel = new com.uiteco.components.RoundedGradientPanel();
        slideShow_AutoSlide = new com.uiteco.OfCuocThiPanel.firstPage.slideShow.SlideShow_AutoSlide();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 243, 244));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        roundedGradientPanel.setColor1(new java.awt.Color(252, 225, 208));
        roundedGradientPanel.setColor2(new java.awt.Color(221, 108, 214));
        roundedGradientPanel.setPreferredSize(new java.awt.Dimension(1370, 730));
        roundedGradientPanel.setRoundBottomLeft(55);
        roundedGradientPanel.setRoundBottomRight(55);
        roundedGradientPanel.setRoundTopLeft(55);
        roundedGradientPanel.setRoundTopRight(55);
        roundedGradientPanel.setLayout(new java.awt.GridBagLayout());

        slideShow_AutoSlide.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 696;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(40, 50, 40, 50);
        roundedGradientPanel.add(slideShow_AutoSlide, gridBagConstraints);

        jLabel1.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        roundedGradientPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        roundedGradientPanel.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(roundedGradientPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.uiteco.components.RoundedGradientPanel roundedGradientPanel;
    private com.uiteco.OfCuocThiPanel.firstPage.slideShow.SlideShow_AutoSlide slideShow_AutoSlide;
    // End of variables declaration//GEN-END:variables
}
