/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.contentPanels.suKienPanel.components;

import com.uiteco.components.RoundedBorder;
import com.uiteco.contentPanels.suKienPanel.components.PaginationModel; // Just to be clear
import java.awt.Color;

/**
 *
 * @author nddmi
 */
public class PaginationView extends javax.swing.JPanel {
    private PaginationModel paginationModel;
    
    /**
     * Creates new form PageBarView
     */
    public PaginationView() {
        initComponents();
        _additionalInit();
    }
    
    public PaginationModel getPaginationModel() {
        return this.paginationModel;
    }
    
    public void setPaginationModel(PaginationModel paginationModel) {
        this.paginationModel = paginationModel;
    }
    
    public void highlight(javax.swing.JComponent comp) {
        comp.setBackground(comp.getBackground().brighter());
    }
    
    public void unHighlight(javax.swing.JComponent comp) {
        comp.setBackground(comp.getBackground().darker());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new test.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        roundedPanel4 = new test.RoundedPanel();
        jLabel2 = new javax.swing.JLabel();
        roundedPanel5 = new test.RoundedPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setPreferredSize(new java.awt.Dimension(810, 35));

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setPreferredSize(new java.awt.Dimension(30, 25));
        roundedPanel1.setRoundBottomLeft(10);
        roundedPanel1.setRoundBottomRight(10);
        roundedPanel1.setRoundTopLeft(10);
        roundedPanel1.setRoundTopRight(10);
        roundedPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("1");
        roundedPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(roundedPanel1);

        roundedPanel4.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel4.setPreferredSize(new java.awt.Dimension(30, 25));
        roundedPanel4.setRoundBottomLeft(10);
        roundedPanel4.setRoundBottomRight(10);
        roundedPanel4.setRoundTopLeft(10);
        roundedPanel4.setRoundTopRight(10);
        roundedPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        roundedPanel4.add(jLabel2, java.awt.BorderLayout.CENTER);

        add(roundedPanel4);

        roundedPanel5.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel5.setPreferredSize(new java.awt.Dimension(30, 25));
        roundedPanel5.setRoundBottomLeft(10);
        roundedPanel5.setRoundBottomRight(10);
        roundedPanel5.setRoundTopLeft(10);
        roundedPanel5.setRoundTopRight(10);
        roundedPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("3");
        roundedPanel5.add(jLabel3, java.awt.BorderLayout.CENTER);

        add(roundedPanel5);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        highlight(jLabel2);
        paginationModel.switchPage(2);
    }//GEN-LAST:event_jLabel2MouseClicked


    private void _additionalInit() {
        setPaginationModel(new PaginationModel());
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private test.RoundedPanel roundedPanel1;
    private test.RoundedPanel roundedPanel4;
    private test.RoundedPanel roundedPanel5;
    // End of variables declaration//GEN-END:variables
}
