/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uiteco.contentPanels.suKienPanel.components;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author nddmi
 * @description: A Panel to display a vertical list of events
 * @preferredSize: [786, 444]
 * @layout: Box layout (Y-axis)
 */
public class SuKienListView extends javax.swing.JPanel implements PropertyChangeListener {

    private SuKienListModel suKienListModel;

    public SuKienListView() {
        this.suKienListModel = new SuKienListModel();
        initComponents();
        _populateList();
    }

    public SuKienListView(SuKienListModel suKienListModel) {
        this.suKienListModel = suKienListModel;
        initComponents();
        _populateList();
    }

    @Override
    public void propertyChange(PropertyChangeEvent event) {
        if (event.getPropertyName().equals("suKienListAdded")) {
            SuKienModel eventModel = suKienListModel.getLastSuKien();
            SuKienView eventView = new SuKienView(eventModel);
            this.add(eventView);
        } else if (event.getPropertyName().equals("suKienListRemoved")) {
            this.remove(this.getComponentCount() - 1);
        }
    }

    private void _populateList() {
        this.suKienListModel.addPropertyChangeListener(this);
        for (SuKienModel eventModel : suKienListModel.getSuKienList()) {
            SuKienView eventView = new SuKienView(eventModel);
            this.add(eventView);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
