/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.forum;

/**
 *
 * @author 21H1 HNQA
 */
public class PostPanel extends javax.swing.JPanel {
    private String title;
    private int viewNumber;
    private String postedBy;
    
    /**
     * Creates new form PostPanel
     */
    public PostPanel() {
        //initComponents();
    }
    
    public PostPanel(String title, int viewNumber, String postedBy) {
        this.title = title;
        this.viewNumber = viewNumber;
        this.postedBy = postedBy;
        InitComponents(title, viewNumber, postedBy);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText(this.postedBy);
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 32);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText(this.title);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 11);
        add(jLabel2, gridBagConstraints);

        jLabel3.setText(Integer.toString(this.viewNumber));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("jLabel3");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);
        add(jLabel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    
    private void InitComponents(String title, int viewNumber, String postedBy){
        setPreferredSize(new java.awt.Dimension(1060,70));
        setBackground(new java.awt.Color(243,244,213));
//        jLabel2 = new javax.swing.JLabel();
//        jLabel2.setSize(454,42);
//        jLabel2.setText(title);
//        jLabel3 = new javax.swing.JLabel();
//        jLabel3.setSize(214,42);
//        jLabel3.setText(String.valueOf(viewNumber)+" views");
//        jLabel1 = new javax.swing.JLabel();
//        jLabel1.setSize(235,42);
//        jLabel1.setText(postedBy);
//        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//        this.setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(17, 17, 17)
//                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
//                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(47, 47, 47)
//                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(31, 31, 31))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(15, 15, 15)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addContainerGap(10, Short.MAX_VALUE))
//        );
        //setBorder(javax.swing.BorderFactory.createEtchedBorder());
        //setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(153, 153, 153)));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(javax.swing.Box.createHorizontalStrut(18));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setSize(454,42);
        jLabel2.setText(this.title);
        add(jLabel2);
//        jLabel2.setLineWrap(true); //xuống dòng nếu text dài và vượt quá size của Label, hiện tại chạy 2 câu lệnh này netbeans báo lỗi
//        jLabel2.setWrapStyleWord(true); //xuống dòng theo từ
   
        add(javax.swing.Box.createHorizontalStrut(450));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setSize(214,42);
        jLabel3.setText(String.valueOf(this.viewNumber)+" views");
        add(jLabel3);
        
        add(javax.swing.Box.createHorizontalStrut(230));
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setSize(235,42);
        jLabel1.setText(this.postedBy);
        add(jLabel1);
        //add(javax.swing.Box.createHorizontalStrut(31));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
